workflows:
  android-workflow:
    name: Android Build (auto-detect)
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - |
        # If the repo contains a zip, unzip it here
        ZIP=$(ls -1 *.zip 2>/dev/null | head -n1 || true)
        if [ -n "$ZIP" ]; then unzip -q "$ZIP" -d .; fi

        # Find the folder that has settings.gradle(.kts)
        PROJECT_DIR=$(dirname "$(git ls-files | grep -E 'settings\.gradle(\.kts)?$' | head -n1)")
        if [ -z "$PROJECT_DIR" ]; then echo "No Gradle Android project found"; exit 1; fi
        echo "Project dir: $PROJECT_DIR"
        cd "$PROJECT_DIR"

        # Use wrapper if present, else system gradle
        chmod +x gradlew 2>/dev/null || true
        if [ -x ./gradlew ]; then
          ./gradlew --no-daemon clean assembleDebug
        else
          if ! command -v gradle >/dev/null 2>&1; then
            sudo apt-get update && sudo apt-get install -y gradle
          fi
          gradle --no-daemon clean assembleDebug
        fi
    artifacts:
      - "**/app/build/outputs/**/*.apk"
