workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - chmod +x gradlew || true
      - ./gradlew --no-daemon clean assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
