workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      android:
        image: default
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**.apk
