workflows:
  android-workflow:
    name: Android Build (zip extract)
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - |
        unzip -o sound-app.zip -d .
        chmod +x gradlew 2>/dev/null || true
        if [ -x ./gradlew ]; then
          ./gradlew --no-daemon assembleDebug
        else
          sudo apt-get update && sudo apt-get install -y gradle
          gradle --no-daemon assembleDebug
        fi
    artifacts:
      - app/build/outputs/**/*.apk
